function torques = computeFrictionTorque(robot, dQ_dt, varargin)
%% ----------------------------------------------------------------------- 
% COMPUTEFRICTIONTORQUE( ROBOT, V )
% 
%% -----------------------------------------------------------------------
defaultFrictionModel = 'viscous';
p   = inputParser;
addOptional(p, 'model', defaultFrictionModel);
parse(p, varargin{:});
model = p.Results.model;
timeStep = 1/robot.samplingFrequency;

torques = zeros(1,robot.ndof);
for i = 1:robot.ndof
        if strcmp(model,'lugre')
            [~,F,~,~] = lugreFriction(...
                robot.friction.lugre.Fc(i),...
                robot.friction.lugre.Fs(i),...
                dQ_dt(i),...
                robot.friction.lugre.vs(i),...
                robot.friction.lugre.sigma1(i),...
                robot.friction.lugre.sigma0(i),...
                robot.friction.lugre.sigma2(i),...
                0,...
                timeStep/3,...
                robot.friction.lugre.tspan,...
                robot.friction.lugre.z0(i));
            torques(i)= max(F);
        elseif strcmp(model,'maxwell')
            [~, F]= maxwellSlipFriction(robot.friction.maxwell.n,...
                dQ_dt,...
                robot.friction.maxwell.k,...
                robot.friction.maxwell.c,...
                robot.friction.maxwell.sigma0,...
                robot.samplingFrequency);
            torques(i) = F(i);
        elseif strcmp(model, 'viscous')
            torques(i) = viscousFriction(dQ_dt(i),...
                robot.friction.viscous.Fc(i),...
                robot.friction.viscous.Fs(i));
        else
            error('Unrecongized Friction Model !');
        end
end        
end